# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GpioDevicePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GpioPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField()),
                ('pin_type', models.CharField(choices=[('5V', '5V'), ('3.3V', '3.3V'), ('GND', 'GND'), ('GPIO', 'GPIO'), ('DNC', 'DNC')], max_length=4)),
                ('gpio_number', models.IntegerField(default=None, null=True)),
                ('protocol_type', models.CharField(blank=True, choices=[('I2C', 'I2C'), ('SPI', 'SPI'), ('UART', 'UART')], default=None, max_length=4, null=True)),
                ('protocol_id', models.CharField(blank=True, default=None, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_smartpi.Device')),
            ],
            bases=('django_smartpi.device',),
        ),
        migrations.AddField(
            model_name='gpiodevicepin',
            name='pin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_smartpi.GpioPin'),
        ),
        migrations.AddField(
            model_name='device',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_smartpi.Device'),
        ),
        migrations.CreateModel(
            name='GpioInputDevice',
            fields=[
                ('inputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_smartpi.InputDevice')),
                ('input_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_smartpi.GpioDevicePin')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_smartpi.inputdevice', models.Model),
        ),
    ]
