# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='No Name', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpiodevicepin',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
