# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpioinputdevice',
            name='input_pin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_smartpi.GpioPin'),
        ),
        migrations.AlterField(
            model_name='gpiooutputdevice',
            name='output_pin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_smartpi.GpioPin'),
        ),
    ]
