# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpioinputdevice',
            name='input_pin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_smartpi.GpioDevicePin'),
        ),
        migrations.AlterField(
            model_name='gpiopin',
            name='gpio_number',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gpiopin',
            name='pin_number',
            field=models.IntegerField(unique=True),
        ),
    ]
