# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpiopin',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
