# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartpi', '0002_auto_20160614_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpiopin',
            name='protocol_id',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='gpiopin',
            name='protocol_type',
            field=models.CharField(blank=True, choices=[('I2C', 'I2C'), ('SPI', 'SPI'), ('UART', 'UART')], default=None, max_length=4, null=True),
        ),
    ]
