# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartpi', '0002_auto_20160616_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='parent',
        ),
        migrations.AddField(
            model_name='device',
            name='related_devices',
            field=models.ManyToManyField(blank=True, editable=False, null=True, related_name='_device_related_devices_+', to='django_smartpi.Device'),
        ),
    ]
