# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartpi', '0002_auto_20160615_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_smartpi.Device')),
                ('state', models.BooleanField(default=False)),
            ],
            bases=('django_smartpi.device',),
        ),
        migrations.AddField(
            model_name='gpioinputdevice',
            name='bouncetime',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='gpioinputdevice',
            name='edge_detect',
            field=models.CharField(choices=[('RISE', 'Rising'), ('FALL', 'Falling'), ('BOTH', 'Both')], default='BOTH', max_length=4),
        ),
        migrations.AddField(
            model_name='gpioinputdevice',
            name='pull_up_down',
            field=models.CharField(blank=True, choices=[('PUP', 'Use Internal Pull-Up'), ('PDN', 'Use Internal Pull-Down')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inputdevice',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GpioOutputDevice',
            fields=[
                ('outputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_smartpi.OutputDevice')),
                ('output_pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_smartpi.GpioDevicePin')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_smartpi.outputdevice', models.Model),
        ),
    ]
