# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartpi', '0003_auto_20160616_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_smartpi.Device')),
                ('input_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_smartpi.InputDevice')),
                ('output_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_smartpi.OutputDevice')),
            ],
            bases=('django_smartpi.device',),
        ),
        migrations.AlterField(
            model_name='device',
            name='related_devices',
            field=models.ManyToManyField(blank=True, editable=False, related_name='_device_related_devices_+', to='django_smartpi.Device'),
        ),
    ]
